[package]
name = "tim"
version = "0.1.0"
authors = ["Aakash Patel <aakpat6@gmail.com>"]

[dependencies]
lazy_static = "0.2.8"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
termion = "1.3.0"
